config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :transactions, only: [ :index, :create ]
  resources :categories, only: [ :index, :new, :create ]
  resources :budgets, only: [ :create, :update ]
  get '/profile', to: 'pages#profile', as: 'profile'
  get '/dashboard', to: 'dashboard#dashboard', as: 'dashboard'
  get '/inbox', to: 'transactions#inbox', as: 'inbox'
  get '/import', to: 'pages#import', as: 'import'
  patch '/cat_next_month', to: 'categories#next_month', as: 'cat_next_month'
  patch '/cat_prev_month', to: 'categories#prev_month', as: 'cat_prev_month'
  patch '/confirm/:id', to: 'transactions#confirm', as: 'confirm'
  patch '/set_category/:id/:category_id', to: 'transactions#set_category', as: 'set_category'
  get '/testpage', to: 'pages#testpage', as: 'testpage'
  patch '/trans_next_month', to: 'transactions#next_month', as: 'trans_next_month'
  patch '/trans_prev_month', to: 'transactions#prev_month', as: 'trans_prev_month'
  get '/spent_data', to: 'dashboard#spent_data', as: 'spent_data'
  get '/balance_data', to: 'dashboard#balance_data', as: 'balance_data'
  get '/budgeted_data', to: 'dashboard#budgeted_data', as: 'budgeted_data'
  patch '/dash_next_month', to: 'dashboard#next_month', as: 'dash_next_month'
  patch '/dash_prev_month', to: 'dashboard#prev_month', as: 'dash_prev_month'
  get '/categorize', to: 'transactions#categorize', as: 'categorize'

end

app/views/pages/dashboard.html.erb
<div class="chart-view">
<div class="container-left nav">
<!--     <ul id="dashboard-tab" class="nav info-card-div"> -->

    <div class="info-card month">
      <%#= render 'components/month_selector' %>
      <div class="month-selector" id="monthSelectorGroup" data-selected-month="<%= @selected_month %>" >
        <%= link_to dash_prev_month_path, method: :patch, remote: true do %>
          <%= icon('fas', 'chevron-left', id: "prevMonth") %>
        <% end %>
        <h4 id="monthSelector"><%= @selected_month %></h4>
        <%= link_to dash_next_month_path, method: :patch, remote: true do %>
          <%= icon('fas', 'chevron-right', id: "nextMonth") %>
        <% end %>
      </div>

    </div>
    <div class="info-card">
      <h5>Money in:</h5>
    </div>
    <div class="info-card">
      <h5>Money out:</h5>
    </div>

  <!-- Tabs -->
  <div id="dashboard-tab">
      <div class="info-card-graph active" data-id="balance">
        <div class="info-card-graph-header">
          <h5>Balance</h5>
          <h5>13 123 kr</h5>
        </div>
        <canvas id="tab-balance-chart" width="200%" height="75%"></canvas>
      </div>
      <div class="info-card-graph" data-id="spent">
        <div class="info-card-graph-header">
          <h5>Spent</h5>
          <h5>8342 kr</h5>
        </div>
        <canvas id="tab-spent-chart" width="200%" height="75%"></canvas>
      </div>
      <div class="info-card-graph" data-id="budgeted">
        <div class="info-card-graph-header">
          <h5>Budgeted</h5>
          <h5>11 357 kr</h5>
        </div>
        <canvas id="tab-budgeted-chart" width="200%" height="75%"></canvas>
      </div>
   <!--  </ul> -->
  </div>
</div>

    <!-- Tab panels -->
<div class="chart-container">
    <div class="tab-content">
      <div class="tab-pane active" id="balance">
        <h4 class="mt-2 mb-4">Balance Panel Content</h4>
        <canvas id="balance-chart" width="400" height="240"></canvas>
      </div>
      <div class="tab-pane" id="spent">
        <h4 class="mt-2 mb-4">Spent Panel</h4>
        <canvas id="spent-chart" width="400" height="240"></canvas>
      </div>
      <div class="tab-pane" id="budgeted">
        <h4 class="mt-2 mb-4">Budgeted Panel</h4>
        <canvas id="budgeted-chart" width="400" height="240"></canvas>
      </div>
    </div>
  </div>
</div>

  <!-- <canvas id="line-chart" width="500" height="250"></canvas> -->
  <!-- <canvas id="tab-balance-chart" width="500" height="250"></canvas> -->

<%= javascript_pack_tag 'chart' %>

app/views/pages/home.html.erb
<body id="home">
<div class="home-container">
  <div class="home-left">
    <div class="home-logo">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= cl_image_tag "yield-resources/logo-v1_kpyze4.png" %>
      <% end %>
    <div class="home-text">
      <h2 class="subtitle"> Manage your money. </h2>
      <h3 class="value-proposition"> Budgeting with Yield is forward-looking and proactive. Newfound awareness of where your money goes will help you gain control over your spendings. </h3>
      <div class="text-right">
        <%= link_to "Get started", new_user_registration_path, class: "form-buttons btn home" %>
      </div>
    </div>
    </div>
  </div>
  <div class="home-right">
    <%= cl_image_tag "yield-resources/landingpage_screenshot_ue3ldg.png" %>
  </div>
</div>

app/views/pages/import.html.erb
<div class="container import-container">
<%= simple_form_for :transactions, url: transactions_path do |f| %>
  <%= f.input_field :file, as: :file %>
  <%= f.submit 'upload' %>
<% end %>
</div>

app/views/pages/profile.html.erb
<div class="container settings-container">

  <div class="categories">

    <p class="define-category">My categories:</p>
    <div class="my-categories">
      <% current_user.categories.each do |category| %>
      <% unless category.no_cat? %>
      <%= render 'components/category', category: category %>
      <% end %>
      <% end %>
    </div>
  </div>
  <div class="adding-category">
    <p class= form-title>Add a category</p>
    <div class="category-container">
      <%= render "categories/form", category: @category %>

    </div>
  </div>
</div>

    <%= javascript_pack_tag "profile" %>

app/views/pages/testpage.html.erb
<!-- <h1> This is the H1. YIELD. </h1>
<h2> This is the H2. It can be used for the value proposition.</h2>
<h3> This is the H3. Could be use for the text inside cards</h3>
<h4> This is h4. This will be text inside the category cards</h4>
<h5> This is h5. It can be use for toolboxes. It is very nice. </h5>
 -->


 <div class="container">

  <%= render 'components/csv_upload' %>
 </div>