config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :transactions, only: [ :index, :create ]
  resources :categories, only: [ :index, :new, :create ]
  resources :budgets, only: [ :create, :update ]
  get '/profile', to: 'pages#profile', as: 'profile'
  get '/dashboard', to: 'dashboard#dashboard', as: 'dashboard'
  get '/inbox', to: 'transactions#inbox', as: 'inbox'
  get '/import', to: 'pages#import', as: 'import'
  patch '/cat_next_month', to: 'categories#next_month', as: 'cat_next_month'
  patch '/cat_prev_month', to: 'categories#prev_month', as: 'cat_prev_month'
  patch '/confirm/:id', to: 'transactions#confirm', as: 'confirm'
  patch '/set_category/:id/:category_id', to: 'transactions#set_category', as: 'set_category'
  get '/testpage', to: 'pages#testpage', as: 'testpage'
  patch '/trans_next_month', to: 'transactions#next_month', as: 'trans_next_month'
  patch '/trans_prev_month', to: 'transactions#prev_month', as: 'trans_prev_month'
  get '/spent_data', to: 'dashboard#spent_data', as: 'spent_data'
  get '/balance_data', to: 'dashboard#balance_data', as: 'balance_data'
  get '/budgeted_data', to: 'dashboard#budgeted_data', as: 'budgeted_data'
  patch '/dash_next_month', to: 'dashboard#next_month', as: 'dash_next_month'
  patch '/dash_prev_month', to: 'dashboard#prev_month', as: 'dash_prev_month'
  get '/categorize', to: 'transactions#categorize', as: 'categorize'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def confirm
    @transaction = Transaction.find(params[:id])
    @transaction.approved_at = Time.now
    @transaction.save
  end

  def index
  end

  def next_month
    super
    render action: :change_month
  end

  def prev_month
    super
    render action: :change_month
  end

  def change_month
  end

  def inbox
    unsorted = current_user.transactions.where(approved_at: nil)
    @transactions = (unsorted.sort_by &:datetime).reverse
  end

  def set_category
    @transaction = Transaction.find(params[:id])
    @transaction.category = Category.find(params[:category_id])
    @transaction.save
  end

  def create
    # raise
    Transaction.import_dnb(params['transactions']['file'], current_user)
     # flash[:notice] = "Countries uploaded successfully"
    redirect_to inbox_path
  end

  def categorize
    current_user.categorize_all
    redirect_to inbox_path
  end
end

app/views/transactions/change_month.js.erb
replaceMonth('<%= j @selected_month %>');
replaceTransactions('<%= j render 'components/transaction_list' %>');
listOpen();

app/views/transactions/confirm.js.erb
function confirmTrans() {
  document.getElementById("transaction-<%= @transaction.id %>").classList.add('confirmed')
  document.getElementById("row-selector-<%= @transaction.id %>").classList.remove('display')
  document.getElementById("row-selector-<%= @transaction.id %>").classList.add('hidden')

  if (document.querySelectorAll('.confirmed').length === document.querySelectorAll('.category-selector-div').length) {
    document.getElementById('empty-inbox').classList.remove('hidden')
    document.getElementById('inboxListHeader').classList.add('hidden')
  }


// let nextElementId = document.getElementById("chevron-<%= @transaction.id %>")
//   .parentElement.querySelector(".transaction-arrow")
//   .dataset.nextElementId

// console.log(document.getElementById(nextElementId).parentElement.querySelector('.trans-cat'))
// document.getElementById(nextElementId).parentElement.querySelector('.trans-cat').click()


}


confirmTrans();

app/views/transactions/inbox.html.erb
<div class="inbox-container list-container container">
  <% unless @transactions.empty? %>
    <div class="header">
      <div id="inboxListHeader" class="inbox-list-div list-header">
        <h4>Category</h4>
        <h4>Date</h4>
        <h4>Info</h4>
        <h4>Amount</h4>
        <h4></h4>
      </div>
    </div>
    <div id="inboxListContainer" class="inbox-list-elements">
      <% @transactions.each_with_index do |trans, list_index| %>
        <%= render 'components/transaction_inbox', trans: trans, index: trans.id, list_pos_id: list_index %>
      <% end %>
    </div>
  <% else %>
    <div class="empty-inbox">
      <h1>Your inbox is empty!</h1>
      <%= image_tag "empty_inbox.svg" %>
    </div>
  <% end %>
  <div class="empty-inbox hidden" id="empty-inbox">
    <h1>Good job! Your inbox is empty!</h1>
      <%= image_tag "empty_inbox_baloons.svg" %>
    <p>Time to check how you are doing in the budget!<p>
    </div>
    <div class="flex-container">
      <div class="import-container">
        <%= render 'components/csv_upload' %>
      </div>
    </div>
  </div>
  <%= javascript_pack_tag 'inbox' %>

app/views/transactions/index.html.erb
<div class="container transaction-container list-container">
  <div class="header">
    <div class="transaction-list-div list-header">
      <h4>Category</h4>
      <h4>Date</h4>
      <h4>Info</h4>
      <div class="month-selector" id="monthSelectorGroup" data-selected-month="<%= @selected_month %>" >
        <%= link_to trans_prev_month_path, method: :patch, remote: true do %>
          <%= icon('fas', 'chevron-left', id: "prevMonth") %>
        <% end %>
        <h4 id="monthSelector"><%= @selected_month %></h4>
        <%= link_to trans_next_month_path, method: :patch, remote: true do %>
          <%= icon('fas', 'chevron-right', id: "nextMonth") %>
        <% end %>
      </div>
    </div>
  </div>
  <div id="transactionsListContainer">
      <%= render 'components/transaction_list' %>
  </div>
</div>

<%= javascript_pack_tag 'transactions' %>

app/views/transactions/set_category.js.erb
function updateCategory() {
  const transaction = document.getElementById("category-<%= @transaction.id %>");
  transaction.innerHTML = '<%= j render "components/category", category: @transaction.category %>';
  transaction.parentElement.querySelector(".confirm-trans").parentElement.click()

  innerHTML = '<%= j render "components/category", category: @transaction.category %>';
}

function updateCurrent() {
  let selected = document.getElementById("cat-<%= @transaction.id %>-<%= @transaction.category.id %>");
  current = selected.parentElement.querySelector(".current")
  if (current) {
    current.classList.remove('current');
  }

  selected.classList.add('current')
}

function closeSelector() {
  document.getElementById("row-selector-<%= @transaction.id %>").classList.remove('display');
  document.getElementById("chevron-<%= @transaction.id %>").classList.toggle('turned')
}

updateCategory();
updateCurrent();
closeSelector()